import React from 'react';
import Document, {
    Html, Head, Main, NextScript,
} from 'next/document';

export default class MyDocument extends Document {
    render() {
        return (
            <Html lang="ar" dir="rtl">
                <Head><title>Beatak</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.svg"/>
                </Head>
                <body>
                <Main/>
                <NextScript/>
                </body>
            </Html>
        );
    }
}

