import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Toggle from '/components/ThemeToggle';

export default function Home() {
    return (
        <div >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <div className="container mx-auto">
                    <h1 className="text-lg text-center m-4">TailwindUI/Next.js</h1>
                    <p className="bg-green-600">This is a test of the tailwind next integration.</p>

                </div>
            </main>


        </div>
    )
}
